language: swift
osx_image: xcode9.4
xcode_project: CucumberSwift.xcodeproj # path to your xcodeproj folder
xcode_scheme: CucumberSwift
xcode_destination: platform=iOS Simulator,name=iPhone 8

deploy:
  provider: script
  script: ./deploy_pod.sh
  on:
    branch: master
