name: CI

on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run TESTS
        run: swift test --enable-code-coverage
      # - name: Generate SonarCloud Friendly Coverage Report
      #   run: ./xccov-to-sonarqube-generic.sh ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult > sq-generic.xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: CucumberSwift-coverage.json
          path: .build/debug/codecov/CucumberSwift.json
          retention-days: 1

  sonar_scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Coverage Report
        uses: actions/download-artifact@v2
        with:
          name: CucumberSwift-coverage.json
          path: artifacts
      - name: Rename Paths in Coverage
        run: |
          sed 's+/Users/tylerthompson/workspace/actions-runner/_work/CucumberSwift/CucumberSwift/++g' artifacts/CucumberSwift-coverage.json > CucumberSwift-coverage.json
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_for_package_managers:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install CocoaPods
        run: gem install cocoapods
      - name: Validate SwiftPM BUILDs
        run: fastlane build_swiftpm
      - name: Validate Cocoapods Can Deploy (lib lint)
        run: fastlane cocoapods_liblint