name: Version Bump

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ master ]
    types: [ completed ]

jobs:
  version_bump:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TYLER_PAT }}
      - name: Bump version in Podspec and Plist
        id: bump_version
        run: |
          bundle exec fastlane patch
          VERSION=`/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" Sources/CucumberSwift/Info.plist`
          echo "##[set-output name=version;]$VERSION"
      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] Apply automatic changes"
          tagging_message: "${{ steps.bump_version.outputs.version }}"
          push_options: --force
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TYLER_PAT }}
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}
          release_name: Release ${{ steps.bump_version.outputs.version }}
          body: ''
